# Generated by Django 5.2.3 on 2025-06-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
