# Generated by Django 5.2.3 on 2025-07-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_langitude_chat_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='history',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='image',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('is_from_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doctors.chat')),
            ],
        ),
    ]
