# Generated by Django 5.2.3 on 2025-08-23 17:10

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_hospital_user'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='doctortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Doctor Translation'},
        ),
        migrations.RemoveField(
            model_name='doctortranslation',
            name='tags',
        ),
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
