# Generated by Django 5.2.3 on 2025-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_chat_file_remove_chat_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor_images/default_doctor.png', upload_to='doctor_images/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='hospital_images/default_hospital.png', upload_to='hospital_images/'),
        ),
    ]
