# Generated by Django 5.2.3 on 2025-08-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_chat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds',
            field=models.IntegerField(default=0),
        ),
    ]
