# Generated by Django 5.2.3 on 2025-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_image_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prize',
            field=models.BigIntegerField(default=100000),
        ),
    ]
