# Generated by Django 5.2.3 on 2025-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
