# Generated by Django 5.2.3 on 2025-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_hospital_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prize',
            field=models.CharField(max_length=1000),
        ),
    ]
