# Generated by Django 5.2.3 on 2025-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='banner_image',
            field=models.ImageField(default='hospital_images/default_hospital.png', upload_to='hospital_images/'),
        ),
    ]
