# Generated by Django 5.2.3 on 2025-11-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_hospital_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortranslation',
            name='filedDescription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
