# Generated by Django 5.2.3 on 2025-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctortranslation_fileddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
