# Generated by Django 5.2.3 on 2025-11-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_message_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctortranslation',
            old_name='filedDescription',
            new_name='fieldDescription',
        ),
    ]
